### ISSUE TITLE
powermail with recaptcha

### ISSUE THREAD

**Issue by toccamonium-fe** [in2code-de/powermailrecaptcha#19]
Hi,

We are using cool powermail extension with recaptcha. To make it work, we enabled spamshield. Now, when I enter all required fields, except the recaptcha one, I get this message in FE >

![grafik](https://user-images.githubusercontent.com/55410878/124759093-8f907c80-df2f-11eb-82c6-993d53927bed.png)

As user, I would be confused that I have to set checkbox at recaptcha to be able to send form. Maybe this could be improved?

thx
Florian

**Comment by sbusemann** [comment]
duplicates #13
