### ISSUE TITLE
Powermail v10 / TYPO3 v11 support

### ISSUE THREAD

**Issue by pduersteler** [in2code-de/powermailrecaptcha#24]
On upgrading a project, I just saw that I can't really install this extension because of the dependencies to powermail v8. Is there any plan on an update in the near future?

**Comment by sypets** [comment]
@pduersteler Powermail is available for TYPO3 v11, in fact the latest 10.7.0 requires TYPO3 v11: https://packagist.org/packages/in2code/powermail

Can you update your question or close it?

P.S. we have been using powermail with TYPO3 v11 successfully since summer 2022.

**Comment by cepheiVV** [comment]
> Powermail is available for TYPO3 v11,

This is obviously a request to update `EXT:powermailrecaptcha`, not `EXT:powermail`

**Comment by sbusemann** [comment]
is supported already
