### ISSUE TITLE
Error when form is called after optinAction?

### ISSUE THREAD

**Issue by tastendruecker** [in2code-de/powermailrecaptcha#25]
https://github.com/einpraegsam/powermailrecaptcha/blob/6220109c81bc5d113517ef9e15769364fe53fba2/Classes/Domain/Validator/SpamShield/RecaptchaMethod.php#L110

I think you should consider the case that a recaptcha validation is unnecessary or even worse may lead to errors when called from the optinAction. I would like to suggest to add that case to the condition like so:

`return ($this->getActionName() === 'create' && $confirmationActive) || $this->getActionName() === 'optinConfirm';`

**Comment by sypets** [comment]
Agree. Perhaps you can add a PR?

Also, "powermailcaptcha" is derived from this extension and has the same problem.

See 

* issue: https://github.com/thomasrawiel/powermailcaptcha/issues/16
* PR: https://github.com/thomasrawiel/powermailcaptcha/pull/17

**Comment by neufeind** [comment]
Just stumbled across this issue as well. Not doing the spam-check for optin-confirm made it go away.
Until fixed in the extension a workaround in typoscript is possible as well: https://github.com/in2code-de/powermail/issues/752#issuecomment-1324875732

**Comment by siwa-pparzer** [comment]
same for **checkCreateAction** if you have confirmation page active

**Comment by pixeldesu** [comment]
@sypets I merged in your fix from the other repository into here as well, thank you! This change will be rolled out in the next maintenance release

@siwa-pparzer in case you didn't know this yet, `checkCreateAction` has already been skipped with version https://github.com/in2code-de/powermailrecaptcha/releases/tag/5.2.2
