### ISSUE TITLE
Is it possible to set captcha language?

### ISSUE THREAD

**Issue by baden32** [in2code-de/powermailrecaptcha#26]
The language of message displayed on the captcha box seems to be determined by browser language. Is it possible to force this setup based on the webpage language?

Using in ex. something like
plugin.tx_powermailrecaptcha.lang = fr

Thank you in advance for your help.
Regards,

**Comment by sbusemann** [comment]
It is planned for Version 6 - see #16

**Comment by sbusemann** [comment]
https://projekte.in2code.de/issues/64174

**Comment by pixeldesu** [comment]
This has been added in 3a51fb23f2d57d8bd2308eb4955fad7a0ae4e366 and will be available with the next maintenance release!
