### ISSUE TITLE
TYPO3 V12 compatibility

### ISSUE THREAD

**Issue by mschwemer** [in2code-de/powermailrecaptcha#27]
There will be an EXT:powermailrecaptcha version, which is compatible with TYPO3 core V12. It is currently under development and testing.

If you need early access to this version, please head over to https://www.in2code.de/agentur/typo3-extensions/early-access-programm/ and support our work.

**Comment by akiessling** [comment]
Hey @mschwemer,

powermailrecaptcha is now marked as v12 compatible according to https://www.in2code.de/agentur/typo3-extensions/early-access-programm/ , but i guess we do have some version mismatch with powermail.

https://packagist.org/packages/in2code/powermailrecaptcha#5.2.0 requires powermail `^8.0 || ^9.0 || ^10.0 || ^11.0`, but https://packagist.org/packages/in2code/powermail jumped from v10 to v12 for TYPO3 v12 compatibility. 

Could you update the constraints from 11 to 12?

**Comment by instruccionesaldorso** [comment]
Any updates on the constraints change? We patched it ourselves for the project, but it would be nice to have v12 compatibility officially :)

**Comment by sbusemann** [comment]
Done in EAP (https://projekte.in2code.de/issues/63020) - release will be done soon®
