### ISSUE TITLE
reCaptcha Version?

### ISSUE THREAD

**Issue by asche76** [in2code-de/powermailrecaptcha#31]
i'm not sure, which version exactly is actually meant?

v3/v2 v3 version2? 
the links to google are all wrong/dead:

![image](https://github.com/user-attachments/assets/dd9d0414-ff5b-44d7-acfc-f8720c6ac076)

![image](https://github.com/user-attachments/assets/00f58491-c4ff-42b1-a1bb-53061858c8ad)

best regards

**Comment by sbusemann** [comment]
this extensions supports V2 - within V2 you can choose what you want.

**Comment by asche76** [comment]
thank you
